name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17.0.16
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17.0.16'
          cache: 'gradle'

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build --no-daemon
