name: CI - Java 17.0.16

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    name: Build & Test (Temurin 17.0.16)
    runs-on: ubuntu-latest

    env:
      CI: true
      SPRING_PROFILES_ACTIVE: test  # ensures test-safe config

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17.0.16 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17.0.16'
          cache: gradle

      - name: Verify Java version
        run: |
          java -version
          javac -version

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew clean build --no-daemon

      - name: Upload test reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
          if-no-files-found: ignore
